# Generated by Django 3.2.16 on 2022-11-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentos',
            name='responsavel',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
