# Generated by Django 4.0.1 on 2022-01-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentos',
            name='idUsuario',
        ),
        migrations.AlterField(
            model_name='movimentositem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
