# Generated by Django 2.2.24 on 2021-12-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeSolidariedade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimentosItem',
        ),
    ]
