# Generated by Django 2.2.24 on 2021-12-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeSolidariedade', '0002_delete_movimentositem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[(1, 'Alimento Não Perecível'), (2, 'Remédio'), (3, 'Protetor Solar')], max_length=50),
        ),
    ]
