# Generated by Django 3.2.9 on 2021-12-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeSolidariedade', '0006_auto_20211213_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
