# Generated by Django 3.2.9 on 2021-12-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeSolidariedade', '0007_remove_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
