# Generated by Django 3.2.9 on 2021-12-14 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redeSolidariedade', '0008_auto_20211214_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='cnpj',
            field=models.CharField(blank=True, default='xxx', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='endereco',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='nome',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='entidade',
            name='telefone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='cpfChefeFamilia',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='enderecoChefeFamilia',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='nomeChefeFamilia',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='integrantefamilia',
            name='nome',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='idFamilia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redeSolidariedade.familia'),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redeSolidariedade.usuario'),
        ),
        migrations.AddField(
            model_name='representante',
            name='cpf',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='endereco',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='idEntidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redeSolidariedade.entidade'),
        ),
        migrations.AddField(
            model_name='representante',
            name='nome',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='obsercacao',
            field=models.TextField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='integrantefamilia',
            name='cpf',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='movimentos',
            name='justificativa',
            field=models.TextField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(blank=True, choices=[('a', 'Admin'), ('b', 'User')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redeSolidariedade.representante'),
        ),
        migrations.CreateModel(
            name='MovimentosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redeSolidariedade.item')),
                ('movimentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redeSolidariedade.movimentos')),
            ],
        ),
    ]
