# Generated by Django 3.2.9 on 2021-12-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeSolidariedade', '0009_auto_20211214_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
