from django.urls import path
from . import views

urlpatterns = [
    path('cadastroDoacao/', views.buscacpf, name='Cadastro de Doações'),
    path('realizaDoacao/<int:pk>/', views.movimentos, name='Realizar Doação'),
    path('cadastroDoacao/delete/<int:pk>/', views.excluirDoacao, name='Excluir Doação'),
    path('cadastroEntidade/', views.cadastroEntidade, name='Cadastro de Entidades'),
    path('cadastroEntidade/edit/<int:pk>/', views.editarEntidade, name='Editar Entidade'),
    path('cadastroEntidade/delete/<int:pk>/', views.excluirEntidade, name='Excluir Entidade'),  
    path('cadastroFamilia/', views.cadastroFamilia, name='Cadastro de Famílias'),
    path('cadastroFamilia/edit/<int:pk>/', views.editarFamilia, name='Editar Familia'),
    path('cadastroFamilia/delete/<int:pk>/', views.excluirFamilia, name='Excluir Familia'),
    path('cadastroIntegranteFamilia/', views.cadastroIntegranteFamilia, name='Cadastro de IntegranteFamilia'),
    path('cadastroIntegranteFamilia/edit/<int:pk>/', views.editarIntegranteFamilia, name='Editar IntegranteFamilia'),
    path('cadastroIntegranteFamilia/delete/<int:pk>/', views.excluirIntegranteFamilia, name='Excluir IntegranteFamilia'),
    path('cadastroItem/', views.cadastroItem, name='Cadastro de Itens'),
    path('cadastroItem/edit/<int:pk>/', views.editarItem, name='Editar Item'),
    path('cadastroItem/delete/<int:pk>/', views.excluirItem, name='Excluir Item'),
    path('cadastroCategoriaItem/', views.cadastroCategoriaItem, name = 'Cadastro Categoria Item'),
    path('cadastroCategoriaItem/edit/<int:pk>/', views.editarCategoria, name='Editar Categoria'),
    path('cadastroCategoriaItem/delete/<int:pk>/', views.excluirCategoria, name='Excluir Categoria'),
    path('cadastroRepresentante/', views.cadastroRepresentante, name='Cadastro de Representantes'),
    path('cadastroRepresentante/edit/<int:pk>/', views.editarRepresentante, name='Editar Representante'),
    path('cadastroRepresentante/delete/<int:pk>/', views.excluirRepresentante, name='Excluir Representante'),
    path('cadastroUsuario/', views.cadastroUsuario, name='Cadastro de Usuários'),
    path('cadastroUsuario/delete/<int:pk>/', views.excluirUsuario, name='Excluir Usuario'),
    path('detalhesDoacao/<int:pk>/', views.detalhesDoacao, name='Detalhes Doação'),
    path('detalhesEntidade/<int:pk>/', views.detalhesEntidade.as_view(), name='Detalhes Entidade'),
    path('detalhesFamilia/<int:pk>/', views.detalhesFamilia, name='Detalhes Familia'),
    path('detalhesRepresentante/<int:pk>/', views.detalhesRepresentante.as_view(), name='Detalhes Representante'),
    path('home/', views.home, name='Rede Solidariedade'),
    path('relatorioDoacao/', views.relatorioDoacao, name='Relatório de Doações'),
    path('relatorioEntidade/', views.relatorioEntidade, name='Relatório de Entidades'),
    path('relatorioFamilia/', views.relatorioFamilia, name='Relatório de Familias'),
    path('relatorioUsuario/', views.relatorioUsuario, name='Relatório de Usuarios'),  
    path('listaDoacao/', views.listaDoacao.as_view(), name='Lista de Doações'),
    path('listaFamilia/', views.listaFamilia.as_view(), name='Lista de Familias'),
    path('listaRepresentante/', views.listaRepresentante.as_view(), name='Lista de Representantes'),
    path('listaUsuario/', views.listaUsuario.as_view(), name='Lista de Usuarios'), 
    path('listaItem/', views.listaItem.as_view(), name='Lista de Itens'), 
    path('listaCategoria/', views.listaCategoriaItem.as_view(), name='Lista de Categorias'), 
    path('searchFamiliaByCpf/', views.searchFamiliaByCpf, name='searchFamiliaByCpf'),  
    path('searchEntidadeByName/', views.searchEntidadeByName, name='searchEntidadeByName'), 
    path('searchItemByName/', views.searchItemByName, name='searchItemByName'),   
    path('searchRepresentanteByName/', views.searchRepresentanteByName, name='searchRepresentanteByName'),    
]
