# Generated by Django 3.2.15 on 2022-09-04 19:50

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('telefone', models.CharField(max_length=24)),
                ('nome', models.CharField(max_length=96)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('endereco', models.CharField(max_length=96)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='data de cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=96)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('endereco', models.CharField(max_length=96)),
                ('observacao', models.TextField(blank=True, max_length=96, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='data de cadastro')),
                ('idEntidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.entidade')),
            ],
        ),
    ]
